kind: PersistentVolume
apiVersion: v1
metadata:
  name: pipeline-workspace
  namespace: kubeflow
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/workspace"
